 import * as React from "react";
 import { useState } from "react";
 import fetch from "fetch-everywhere";
 import { Pokemon } from "pokenode-ts";
 import {
  Default,
  GetPath,
  TemplateConfig,
  TemplateProps,
  GetHeadConfig,
  HeadConfig,
 } from "@yext/yext-sites-scripts";
import "../index.css";
import Header, { Link } from "../components/header";
import Footer from "../components/footer";
 
 export const config: TemplateConfig = {
   name: "about",
 };
 
 export const getPath: GetPath<TemplateProps> = () => {
   return `about`;
 };
 
 export const getHeadConfig: GetHeadConfig<TemplateProps> = (props): HeadConfig => {
  return {
    title: "About Page",
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "meta",
        attributes: {
          description: "This site was generated by the Yext SSG",
        },
      },
    ],
  };
};

 const About: Default<TemplateProps> = (props) => {
  const { document } = props;
  const {
    _site, 
  } = document;
 
   return (
    <>
      <div className="centered-container">
      <Header
          links={_site.c_header}
          logo={_site.logo}
        ></Header>
      </div>
      <div className="centered-container">
        <div className="section space-y-10 px-10">
          <h1 className="">About Page</h1>
          <div className="space-y-5">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <p>
              Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
            </p>
          </div>
          <Footer links={_site.c_footer} instagram={_site.instagramHandle} facebook={_site.facebookVanityUrl} twitter={_site.twitterHandle}></Footer>
        </div>
      </div>
    </>
   );
 };
 
 export default About;
 