import * as React from "react";
import Banner from "../components/banner";
import Header, { Link } from "../components/header";
import Footer from "../components/footer";
import Cta from "../components/cta";
import Markdown from 'markdown-to-jsx';
import "../index.css";
import {
  Default,
  GetPath,
  TemplateConfig,
  TemplateProps,
  GetHeadConfig,
  HeadConfig,
} from "@yext/yext-sites-scripts";

export const config: TemplateConfig = {
  stream: {
    $id: "menu",
    fields: [
      "id",
      "uid",
      "meta",
      "name",
      "richTextDescription",
      "photoGallery",
      "slug",
      "c_relatedMenuItems.name",
      "c_relatedMenuItems.id",
      "c_relatedMenuItems.c_itemCategory",
      "c_relatedMenuItems.richTextDescription",
      "c_relatedMenuItems.photoGallery",
      "c_relatedMenuItems.slug"
    ],
    filter: {
      entityTypes: ["ce_menu"],
    },
    localization: {
      locales: ["en"],
      primary: false,
    },
  },
};

export const getPath: GetPath<TemplateProps> = (props) => {
  return `menu`;
};

export const getHeadConfig: GetHeadConfig<TemplateProps> = (props): HeadConfig => {
  return {
    title: props.document.name,
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "meta",
        attributes: {
          description: "This site was generated by the Yext SSG",
        },
      },
    ],
  };
};

const Menu: Default<TemplateProps> = (props) => {
  const { document } = props;
  const {
   _site,
   name,
   richTextDescription,
   photoGallery,
   slug,
   c_relatedMenuItems,
  } = document;

  return (
    <>
      <div className="centered-container">
       <Header
           links={_site.c_header}
           logo={_site.logo}
         ></Header>
      </div>
      <div className="centered-container">
        <div className="section">
           <div className="text-4xl text-center font-bold">Menu Items</div>
               <div className="pt-10 grid gap-y-8 sm:grid-cols-2 lg:grid-cols-3 gap-x-5">
                   
               </div>
           </div>
        <Footer links={_site.c_footer} instagram={_site.instagramHandle} facebook={_site.facebookVanityUrl} twitter={_site.twitterHandle}></Footer>
      </div>
    </>
  );
};

export default Menu;
